antora:
  extensions:
    - require: '@antora/lunr-extension'

runtime:
  cache_dir: ./.cache/antora
  fetch: true

site:
  title: Antora Test Playbook
  start_page: testplaybook::index.adoc

content:
  sources:
    - url: https://github.com/r-vanooyen/antora-playbook.git
      branches:
       - main
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: ./supplemental-ui
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll

asciidoc:
  attributes:
    kroki-fetch-diagram: false
    allow-uri-read: true
  extensions:
    - asciidoctor-kroki
    - ./lib/inline-puml-link-macro.js
